### PR TITLE
Create an abstraction over WebSocket to be used with both dart:io and dart:html

### LINKED ISSUE #190: Error on flutter web. Platform._environment
I'm using flutter web on Windows, but I'm getting this message: 'Platform._environment'.
Also, the **.local-chromium** folder is not being created after calling puppeteer on my code.

Any hints? :)

### PR DESCRIPTION
**Pull request by xvrh**
Fixes #190

### CODE REVIEW

**Comment by hacker1024** [comment]
Thanks for this @xvrh.

Are you aware of the [`web_socket_channel`](https://pub.dev/packages/web_socket_channel) package, though? You seem to have partially duplicated it, and it might be worth using as it's maintained by the Dart team.

**Comment by xvrh** [comment]
@hacker1024 yeah, I've used this package in some other projects. 

I evaluated it for this case but ultimately decided that it's not worth it here.
The abstraction layer and the web implementation is so small that (I think) it's a better strategy than adding a new dependency...

I can change my mind, if you see some other advantages...

**Comment by Joseph-Nathan** [comment]
`Error: Unsupported operation: Platform._environment
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49         throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 284:5                      _environment
dart-sdk/lib/io/platform_impl.dart 83:17                                             get environment
dart-sdk/lib/io/platform.dart 168:59                                                 get environment
packages/puppeteer/src/puppeteer.dart 269:71                                         defaultArgs
packages/puppeteer/src/puppeteer.dart 112:28                                         launch
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                   runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                   _async
packages/puppeteer/src/puppeteer.dart 93:25                                          launch
packages/MyProject/MyFile.dart 18:35                                               MyFunctionName
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                   runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                   _async
packages/MyProject/MyFile.dart 17:15                                               MyFunctionName`

i get this when try to use it with flutter web , on mac
puppeteer: 2.17.0
fultter: 3.3.6

**Comment by xvrh** [comment]
@Joseph-Nathan it is this test file: https://github.com/xvrh/puppeteer-dart/blob/master/test/connect_on_web_test.dart
Basically the steps are:
- Start a browser with `puppeteer.launch`
- Start an http server to serve index.html and script.js
- Compile a dart script with `dart compile js`
- Go to index.html with puppeteer (which will load script.js)
- index.html page will contain `<body x-puppeteer-endpoint="<url of puppeteer">`
- Let the script in the browser connect back to the host and basically communicate with itself. 🤪

**Comment by Joseph-Nathan** [comment]
@xvrh  hi ,
i start the browser and get `browser.wsEndpoint` ,
and used it from my web page by `puppeteer.connect(browserWsEndpoint: "xxx" )`
now i can open new page , but when i tried to controll the page i got this :


``
Error: TimeoutException: Navigation Timeout Exceeded: 30000ms exceeded
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 299:10  createErrorWithStack
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 341:28            _throw
dart-sdk/lib/core/errors.dart 116:5                                           throwWithStackTrace
dart-sdk/lib/async/zone.dart 1378:11                                          callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
``

**Pull request merged**
